<!--
Для файла views\scripts\person-compare\formUserDivision.phtml
Функция выбора всех чекбоксов внутри collapseid 
<input  type="checkbox" onclick="checkAll(this)" id ="$type->getId()">

-->
<script>
function checkAll(obj) {
  'use strict';
  var id = 'collapse' + obj.id;
  var items = document.getElementById(id);
  var inputs = items.getElementsByTagName("input");
  for ( var i = 0; i < inputs.length; i++ )
    if ( (inputs.item(i).type) && (inputs.item(i).type==="checkbox" ) )
      inputs.item(i).checked = obj.checked;
}
</script>

<h5>Выберите предприятия :</h5>
<?=$this->form?>
