<script type="text/javascript" src="/js/selectAjax.js"></script>
<script> urlRedirectSelect = '/question/select';</script>

<div class="col-sm-6">
<h4>Добавление вопроса</h4>
<?= $this->form;?>
    
    
<a  class="btn-default btn pull-left"  style="text-decoration: none"
    href="<?=$this->url(array('controller' => 'question', 'action' => 'load'),'default');?>">
    <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Отмена</a>
</div>


