
<div class="col-sm-6">
<h4>Редактирование <?=Services_DictionaryService::getDictionaryChapterFromSession()->getFname_roditelni();?></h4>
<?= $this->form;?>
<a  class="btn-default btn pull-left"  style="text-decoration: none"
    href="<?=$this->url(array('controller' => 'chapter', 'action' => 'load'),'default');?>">
    <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Отмена</a>
</div>