
    <div class="modal-dialog modal-lg">
        <div class="modal-content ">
            <div class="modal-footer">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <h4 class="panel-title text-left">
                            <span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;Внимание! 
                        </h4>
                    </div>
                    <div class="panel-body text-left alert-warning">
                        <div  class=" h4 text-warning"> 
                            <p>Нет пользователей в системе по выбранным Вами предприятиям ! </p>                           
                        </div>

                        <a class="btn  btn-warning pull-right"  role="button" 
                           href="<?= $this->url(array('controller' => 'user', 'action' => 'add'), 'default'); ?>">
                            <span class="glyphicon glyphicon-plus" ></span>&nbsp;Добавить пользователя </a>
                        <a class="btn  btn-default pull-right"  role="button"  style="margin-right: 20px;"
                           href="<?= $this->refUrl; ?>">
                            <span class="glyphicon glyphicon-ok"></span>&nbsp;Позже</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
