<style>
    .check {
        padding-top: 20px;
    }
</style>
<div class="text-left">
    <h4>Добавление темы экзамена</h4>
    <div class="col-sm-5"><?= $this->form;?></div>   
    <div class="clearfix"></div>
<a  class="btn-default btn pull-left"  style="text-decoration: none"
    href="<?=$this->url(array('controller' => 'adminExam', 'action' => 'load-theme'),'default');?>">
    <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Отмена</a></td>
</div>