<script type="text/javascript" src="/js/jquery-ui.datepicker.js"></script>
<script type="text/javascript" src="/js/datepicker.options.js"></script>
<script type="text/javascript" src="/js/scheduleAuthType.options.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" /> 

<div class="col-sm-6 text-left">
    <h4>Редактирование расписания экзамена </h4>
<?= $this->form;?>
    
  
<a  class="btn-default btn pull-left"  style="text-decoration: none"
    href="<?=$this->refUrl;?>">
    <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Отмена</a></td>
</div>