<style>
    a {
        color: black;
    }
    a:hover {
        color: #04519b;
    }
</style>
<form action="<?= $this->escape($this->form->getAction()) ?>"
      method="<?= $this->escape($this->form->getMethod()) ?>">
    <input type ="hidden" value ="<?= $this->scheduleId ?>" name="scheduleId"/>
    <div class="col-sm-12">
        <div class="col-sm-4">
            <div class="list-group">
                <h3 class="list-group-item active list-group-item-heading">Все пользователи</h3>

                <?php
                if ($this->users != null) :
                    foreach ($this->users as $user) :

                        $idu = $user->getId();
                        $userId = "user$idu";
                        ?>

                        <label class="list-group-item text-left">                 
                            <input type="checkbox" value="1" name ="source_<?= $idu ?>">
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <a target="blank" href="<?= $this->url(array('id' => $idu), 'userEdit') ?>"><kbd><?= $user->getSubDivision()->getSname() ?></kbd>
                                <?= $this->form->$userId->getLabel() ?> 
                            </a>
                        </label>

                        <?php
                    endforeach;
                endif;
                ?>

            </div>
        </div>
        <div class="col-sm-8">
            <div class="list-group">
                <h3 class="list-group-item active list-group-item-heading">Допущенные пользователи
                    <button  name="submit"                                    
                             value="изменить" class="btn-sm  btn-primary pull-right" type="submit">
                        изменить &nbsp;<span class="glyphicon glyphicon-refresh"></span>
                    </button>
                </h3>

                <?php
                if ($this->acceptedUsers != null) :
                    foreach ($this->acceptedUsers as $acceptedUser) :

                        $idu = $acceptedUser->getUser()->getId();
                        $userId = "acceptedUser$idu";
                        ?>

                        <label class="list-group-item text-left">
                            <input type ="hidden" value ="0" name="destination_<?= $idu ?>"/>
                            <input type="checkbox" value="1" checked="checked" name ="destination_<?= $idu ?>">
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <a target="blank" href="<?= $this->url(array('id' => $idu), 'userEdit') ?>">
                                <kbd>
                                    <?= $acceptedUser->getUser()->getSubDivision()->getSname() ?>
                                </kbd>
                                <?= $this->form->$userId->getLabel() ?>
                            </a>
                            <span class="pull-right">
                                <i>попыток: 
                                <?php echo ($acceptedUser->getTry()>0) ? $acceptedUser->getTry() : 'без ограничений' ?>
                                </i>
                            </span>
                        </label>

                        <?php
                    endforeach;
                endif;
                ?>

            </div>
        </div>

    </div>



</form>
