<?php include "../public/include/dataTables.phtml"; ?>

<div class="col-sm-8">
<table class='defaultColor table table-hover  table-bordered ' align="center" id ="dataTable">
    <caption><h4>Список критериев сдачи экзамена</h4></caption>
    <thead class="text-center">




        <tr style="font-weight: bold;">
            <th>Значение критерия</th>
            <th>Измерение</th>
            <?php if ($this->roleId == 1) { ?>
                    <th>Отделение</th>
                    
                <?php } ?>
            <th class="noSort"></th>
            <th class="noSort"></th>
            <th class="noSort"></th>
        </tr>
    </thead>
    <tbody>
             <?php if($this->criterions == null ) { ?>
        
    <td colspan="4" class="text-center">Не найдено записей </td><td>
        <a   data-toggle="tooltip" title="добавить"  href="<?= $this->url(array('controller' => 'criterion', 'action' => 'add'), 'default'); ?>">
                        <span class="glyphicon glyphicon-plus" style="color:green"></span>
                    </a>
    </td>
        <?php } ?>
        <?php foreach ($this->criterions as $criterion) { ?>
            <tr>
                <td><?= $criterion->getValue() ?></td>
                <td><?= $criterion->getMeasure() ?></td>
                <?php if ($this->roleId == 1) { ?>
                    <td><?= $criterion->getDivision()->getSname() ?></td>
                    
                <?php } ?>
                


                <td class="text-right ">
                    <a   title="удалить"  data-toggle="modal" data-target="#myModal<?=$criterion->getId()?>">
                        <span class="glyphicon glyphicon-remove" style="color:red"></span>
                    </a>
                    
                </td>    
                    
                    <!-- Modal window-->
                    <div class="modal fade" id="myModal<?=$criterion->getId()?>" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-body ">
                                    <h4>Вы действительно хотите удалить этот раздел  ?</h4>
                                </div>
                                <div class="modal-footer ">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                        <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Отменить</button>
                                    <a class="btn btn-danger"  role="button" 
                                       href="<?= $this->url(array('id' => $criterion->getId()), 'criterionDelete') ?>">
                                        <span class="glyphicon glyphicon-remove"></span>&nbsp;Удалить</a>
                                </div>
                            </div>

                        </div>
                    </div>

                
                <td class="text-right ">
                    <a   data-toggle="tooltip" title="редактировать"  href="<?= $this->url(array('id' => $criterion->getId()), 'criterionEdit') ?>">
                        <span class="glyphicon glyphicon-pencil" style="color:orange"></span>
                    </a>
                </td>
                <td class="text-right">
                    <a   data-toggle="tooltip" title="добавить"  href="<?= $this->url(array('controller' => 'criterion', 'action' => 'add'), 'default'); ?>">
                        <span class="glyphicon glyphicon-plus" style="color:green"></span>
                    </a>
                </td>
            </tr>
        <?php } ?>

    </tbody>
    <tfoot></tfoot>
</table>
</div>








