<?php include_once "../public/include/dataTables.phtml"; ?>
<table class='defaultColor table table-hover  table-bordered ' align="center" id ="dataTable">
    <caption><h4>Список пользователей</h4></caption>
    <thead class="text-center">

        
        <tr style="font-weight: bold;">
            <th>ФИО</th>
            <th>Логин</th>
            <th>Должность</th>
            <th>Роль</th>
            <th>Предприятие</th>
            <?php if ($this->roleId == 1) { ?>  
                <th>Отделение</th>                
                <th>Архив</th>
            <?php } ?>
            <th class="noSort"></th>    
            <th class="noSort"></th>
            <th class="noSort"></th>
        </tr>
    </thead>
    
    
    
    
    <tbody>  
        <?php if( Services_UserSubDivisionService::getInstance()->fetchByManagerInArray(Zend_Auth::getInstance()->getIdentity()) == null) 
            { 
        ?>
        <td colspan="7" class="text-center">Не найдено выбранных предприятий!</td><td>
        <a   data-toggle="tooltip" title="добавить"  href="<?= $this->url(array('controller' => 'PersonCompare', 'action' => 'index'), 'default'); ?>">
                        <span class="glyphicon glyphicon-wrench"></span>
                    </a>
    </td>
        
        <?php        
            } 
        else {              
            ?>       
        
        <?php if($this->users == null  ) { ?>        
    <td colspan="7" class="text-center">Не найдено записей </td><td>
        <a   data-toggle="tooltip" title="добавить"  href="<?= $this->url(array('controller' => 'user', 'action' => 'add'), 'default'); ?>">
                        <span class="glyphicon glyphicon-plus" style="color:green"></span>
                    </a>
    </td>
    
    
        <?php } else { ?>
        <?php foreach ($this->users as $user) { ?>
            <tr>
                <td><?= $user->getFIO() ?></td>
                <td><?= $user->getLogin() ?></td>
                <td><?= $user->getPost()->getSname() ?></td>
                <td><?= $user->getRole()->getSname() ?></td>
                <td><?= $user->getSubDivision()->getSname() ?></td>
                <?php if ($this->roleId == 1) { ?>

                    <td><?= $user->getDivision()->getSname(); ?></td>

                    <td><?php if ($user->getArchive() == '0') { ?> 
                            нет 

                        <?php } ?>
                        <?php if ($user->getArchive() == '1') { ?> 
                            да
                        <?php } ?>
                    </td>                                 

                <?php } ?>
                <td class="text-right ">
                    <a   title="удалить"  data-toggle="modal" data-target="#myModal<?= $user->getId() ?>">
                        <span class="glyphicon glyphicon-remove" style="color:red"></span>
                    </a>

                </td>    

                <!-- Modal window-->
        <div class="modal fade" id="myModal<?= $user->getId() ?>" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body ">
                        <h4>Вы действительно хотите удалить этого пользователя  ?</h4>
                    </div>
                    <div class="modal-footer ">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Отменить</button>
                        <a class="btn btn-danger"  role="button" 
                           href="<?= $this->url(array('id' => $user->getId()), 'userDelete') ?>">
                            <span class="glyphicon glyphicon-remove"></span>&nbsp;Удалить</a>
                    </div>
                </div>

            </div>
        </div>


        <td class="text-right ">
            <a   data-toggle="tooltip" title="редактировать"  href="<?= $this->url(array('id' => $user->getId()), 'userEdit') ?>">
                <span class="glyphicon glyphicon-pencil" style="color:orange"></span>
            </a>
        </td>
        <td class="text-right">
            <a   data-toggle="tooltip" title="добавить"  href="<?= $this->url(array('controller' => 'user', 'action' => 'add'), 'default'); ?>">
                <span class="glyphicon glyphicon-plus" style="color:green"></span>
            </a>
        </td>
    </tr>
        <?php } ?>
    <?php } ?>  
    <?php } ?>  
</tbody>
<tfoot></tfoot>
</table>









