<div class="container">
    <div class="h3 text-uppercase text-center"><?= $this->exam->getFname() ?></div>
    <div class="h4 text-uppercase text-center"><?= $this->schedule->getDateStart() ?> - <?= $this->schedule->getDateStart() ?></div>

    <div class="clearfix"></div>

    <!-- Комиссия-->    
    <?php if ($this->exam->getCommittee() != null) { ?>
        <div class="row h5">
            <div class= "col-sm-2">
                <strong> Комиссия :</strong>
            </div>
            <div class= "col-sm-10">
                <?= $this->exam->getCommittee() ?>
            </div>
        </div>
    <?php } ?>
    <!--  /Комиссия-->    


    <!-- Экзаменатор-->    
    <div class="row h5">
        <div class= "col-sm-2">
            <strong> Экзаменатор :</strong> 
        </div>
        <div class= "col-sm-4">
            <?= $this->exam->getManager()->getFIO() ?>
            &nbsp;&nbsp; 
            <?= $this->schedule->getManager()->getDivision()->getSname() ?> 
        </div>
    </div>
    <!-- / Экзаменатор-->    

    <!-- Предприятие-->    
    <div class="row h5">
        <div class= "col-sm-2">
            <strong> Предприятие :</strong>
        </div>
        <div class= "col-sm-4">
            <?= $this->exam->getSubDivision()->getSname() ?> 
        </div>
    </div>
    <!-- /Предприятие-->    


        <div class="row h5">
            <div class= "col-sm-2">
                <strong> Допущенные пользователи :</strong> 
            </div>
            <div class="col-sm-4">
                <?php
                foreach ($this->usersExam as $ue) {
                    echo $ue->getUser()->getFIO() . '   ' . $ue->getUser()->getSubDivision()->getSname();
                    echo '<br>';
                }
                ?>
            </div>
        </div>

    <!--Регистрация-->
    <div class="row h5" style="padding-top: 50px;">
        <div class= "col-sm-2">
            <strong>Регистрация </strong>
        </div>
        
        <div class="col-sm-7 ">
                <?php if ($this->exam->getTypeAuth() == 1) { ?>

                    <form class="form-inline" role="form">
                        <div class="form-group">
                            <select name="user_id" id="user_id" class="form-control" required="required">
                             <?php  foreach ($this->usersExam as $ue) { ?>   
                            <option value="<?=$ue->getUser()->getId()?>"><?=$ue->getUser()->getFIO() . '   ' . $ue->getUser()->getSubDivision()->getSname()?></option>
                             <?php  } ?>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="sr-only" for="exampleInputPassword2">Пароль</label>
                            <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Пароль">
                        </div>
                        <button type="submit" class="btn btn-default">Войти</button>
                    </form>

                <?php } else {
                    ?>
                    <form class="form-inline" role="form">
                        <div class="form-group">
                            <label class="sr-only" for="login">Логин</label>
                            <input type="text" class="form-control" id="login" placeholder="Имя пользователя" required="required">
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="exampleInputPassword2">Пароль</label>
                            <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Пароль" required="required" >
                        </div>
                        <button type="submit" class="btn btn-default">Войти</button>
                    </form>

                <?php } ?>
        </div>
    </div>

        <!--  /Регистрация-->

</div>
