<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
     <h4 class="modal-title">Добавить тип предприятия</h4>
     <h4 class="text-center"><?=$this->division?></h4>

</div>
<div class="modal-body">
    
<?=$this->form ?>   

    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
</div>

     
     
