<script type="text/javascript" src="/js/selectAjax.js"></script>
<script> urlRedirectSelect = '/subDivision/select';</script>
<div class="col-sm-6">
<h4>Редактирование предприятия</h4>
<?= $this->form;?>
<a  class="btn-default btn pull-left"  style="text-decoration: none"
    href="<?=$this->url(array('controller' => 'subDivision', 'action' => 'load'),'default');?>">
    <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Отмена</a></td>
</div>