<div class="col-sm-6">



    <div class="panel panel-success">
         <div class="panel-heading">
    <h4 class="panel-title text-left">Вопрос</h4>
    </div>
        <div class="panel-body text-left alert-success">
            <h4><?=$this->question->getText(); ?></h4>
        </div>
    </div>
    <?= $this->form; ?>


    <a  class="btn-default btn pull-left"  style="text-decoration: none"
        href="<?= $this->refUrl; ?>">
        <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Отмена</a></td>
</div>


